/**
 * 365 raisons pour lesquelles je t'aime
 *
 * ─ Jour 1 = 14 février 2026
 * ─ Jour 365 = 13 février 2027
 *
 */

/* eslint-disable max-len */
var REASONS = [
    /* 1  */ "Parce que ton sourire illumine chacune de mes journées",
    /* 2  */ "Pour la façon dont tu me regardes quand tu crois que je ne te vois pas",
    /* 3  */ "Parce que tu me fais rire comme personne d'autre",
    /* 4  */ "Pour ta patience infinie avec mes petits défauts",
    /* 5  */ "Parce que tu es la première personne à qui j'ai envie de raconter ma journée",
    /* 6  */ "Pour la douceur de tes mains dans les miennes",
    /* 7  */ "Parce que tu crois en moi même quand j'en doute",
    /* 8  */ "Pour chaque « bonne nuit » que tu m'envoies sans jamais oublier",
    /* 9  */ "Parce que tu rends les jours ordinaires extraordinaires",
    /* 10 */ "Pour ta façon de me réconforter quand rien ne va",
    /* 11 */ "Parce que tu es mon chez-moi, où que l'on soit",
    /* 12 */ "Pour les petites attentions que tu as au quotidien",
    /* 13 */ "Parce que tu me connais mieux que quiconque",
    /* 14 */ "Pour la chaleur de tes bras quand il fait froid dehors",
    /* 15 */ "Parce que tu acceptes mes humeurs sans me juger",
    /* 16 */ "Pour chaque fou rire partagé ensemble",
    /* 17 */ "Parce que tu es belle, dedans comme dehors",
    /* 18 */ "Pour ta détermination qui m'inspire chaque jour",
    /* 19 */ "Parce qu'avec toi le silence n'est jamais gênant",
    /* 20 */ "Pour la passion que tu mets dans tout ce que tu fais",
    /* 21 */ "Parce que tu me pousses à devenir une meilleure personne",
    /* 22 */ "Pour la magie que tu apportes dans les moments simples",
    /* 23 */ "Parce que tu es ma première et dernière pensée de chaque journée",
    /* 24 */ "Pour ta générosité sans limite envers ceux que tu aimes",
    /* 25 */ "Parce que tu me manques dès que tu n'es plus là",
    /* 26 */ "Pour ta voix qui est ma mélodie préférée",
    /* 27 */ "Parce que tu sais exactement comment me remonter le moral",
    /* 28 */ "Pour le bonheur que je lis dans tes yeux",
    /* 29 */ "Parce que tu as choisi d'être avec moi, et ça me rend fier chaque jour",
    /* 30 */ "Pour ta façon de danser quand tu crois que personne ne regarde",
    /* 31 */ "Parce que chaque moment passé avec toi est un trésor",
    /* 32 */ "Pour ta capacité à voir le positif en toute chose",
    /* 33 */ "Parce que tu me fais voir le monde différemment",
    /* 34 */ "Pour la tendresse de chacun de tes gestes",
    /* 35 */ "Parce que tu es mon aventure préférée",
    /* 36 */ "Pour ton courage face aux difficultés de la vie",
    /* 37 */ "Parce que tu as le pouvoir de me calmer d'un simple regard",
    /* 38 */ "Pour tous les petits plats que tu prépares avec amour",
    /* 39 */ "Parce que tu ris de mes blagues même les plus nulles",
    /* 40 */ "Pour ta loyauté indéfectible",
    /* 41 */ "Parce que tu sens incroyablement bon :)",
    /* 42 */ "Pour ta façon de t'endormir contre moi",
    /* 43 */ "Parce que tu sais me surprendre encore et toujours",
    /* 44 */ "Pour ta curiosité qui nous fait découvrir de nouvelles choses",
    /* 45 */ "Parce que tu es la meilleure partenaire de vie imaginable",
    /* 46 */ "Pour chaque message qui me fait sourire en pleine journée",
    /* 47 */ "Parce que tu ne lâches jamais rien, et ça force l'admiration",
    /* 48 */ "Pour ta créativité débordante",
    /* 49 */ "Parce que tu as fait de ma vie une véritable histoire d'amour",
    /* 50 */ "Pour les projets qu'on construit ensemble, un par un",
    /* 51 */ "Parce que tu es drôle sans même t'en rendre compte (un vrai clown hihi 😁",
    /* 52 */ "Pour ta façon de prendre soin de ceux que tu aimes",
    /* 53 */ "Parce que tu me donnes envie de me lever chaque matin",
    /* 54 */ "Pour le frisson que je ressens encore quand tu me touches",
    /* 55 */ "Parce que tu es à la fois ma meilleure amie et mon amour",
    /* 56 */ "Pour la confiance que tu m'accordes au quotidien",
    /* 57 */ "Parce que tu as transformé ma vie depuis qu'on se connaît",
    /* 58 */ "Pour tous les films qu'on regarde blottis l'un contre l'autre",
    /* 59 */ "Parce que tu es la plus belle rencontre de ma vie",
    /* 60 */ "Pour ta patience quand je suis un peu trop têtu ",
    /* 61 */ "Parce que tes yeux pétillent quand tu parles de ce que tu aimes",
    /* 62 */ "Pour les batailles d'oreillers qui finissent en câlins, GRrrrr",
    /* 63 */ "Parce que tu me voles les couvertures et que je ne m'en plains même plus",
    /* 64 */ "Pour ta façon de chanter sous la douche, ça va je suis assez épargné 😜",
    /* 65 */ "Parce que chaque repas partagé avec toi est un moment précieux",
    /* 66 */ "Pour les road trips qu'on fait ou qu'on fera ensemble",
    /* 67 */ "Parce que tu as le plus beau rire du monde",
    /* 68 */ "Pour ta façon de ma faire craquer dans ton lit 😏",
    /* 69 */ "Parce que tu es ma personne préférée sur cette Terre 🌍",
    /* 70 */ "Pour les meilleurs pancakes que tu me prépares le matin 🥞",
    /* 71 */ "Parce que tu es incroyablement forte et courageuse 🦸🏽",
    /* 72 */ "Pour toutes les séries qu'on regarde ensemble 📺",
    /* 73 */ "Parce que tu m'apprends des choses nouvelles sans cesse",
    /* 74 */ "Bon anniversaire mon amour 🎁🎁🎁, je t'aime tellement ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️ ",
    /* 75 */ "Parce que tu es la raison pour laquelle je souris sans raison 🙂",
    /* 76 */ "Pour tes yeux dans lesquels je pourrais me perdre",
    /* 77 */ "Parce que tu me comprends sans que j'aie besoin de parler",
    /* 78 */ "Pour ta façon de me serrer dans tes bras",
    /* 79 */ "Parce que tu crois aux mêmes rêves que moi 🌌",
    /* 80 */ "Pour la complicité unique qu'on partage au quotidien",
    /* 81 */ "Parce que tu rends chaque au revoir plus doux avec un simple sourire",
    /* 82 */ "Pour la manière dont tu prends ma main sans même y penser",
    /* 83 */ "Parce que tu sais transformer mes journées compliquées en moments simples",
    /* 84 */ "Pour ton regard qui me rassure instantanément",
    /* 85 */ "Parce que tu es mon plus bel équilibre",
    /* 86 */ "Pour ta capacité à me faire relativiser",
    /* 87 */ "Parce que tu illumines même les jours gris 🌈",
    /* 88 */ "Pour la sincérité de tes émotions",
    /* 89 */ "Parce que tu es mon plus beau hasard devenu évidence",
    /* 90 */ "Pour la façon dont tu me fais sentir important",
    /* 91 */ "Parce que tu crois en nos rêves communs",
    /* 92 */ "Pour ta façon d'écouter vraiment quand je parle",
    /* 93 */ "Parce que tu es mon plus grand soutien",
    /* 94 */ "Pour ton enthousiasme contagieux",
    /* 95 */ "Parce que tu me donnes envie de t'aimer encore plus fort",
    /* 96 */ "Pour la douceur de ta voix quand tu m'appelle doudou 🧸",
    /* 97 */ "Parce que tu rends chaque câlin unique",
    /* 98 */ "Pour ta manière d’être toujours authentique",
    /* 99 */ "Parce que tu es ma plus belle certitude",
    /* 100 */ "Pour les souvenirs qu’on crée à chaque instant",
    /* 101 */ "Parce que tu me surprends encore après tout ce temps",
    /* 102 */ "Pour ta façon de rire quand quelque chose te surprend",
    /* 103 */ "Parce que tu es mon plus beau présent",
    /* 104 */ "Pour la lumière que tu apportes dans ma vie",
    /* 105 */ "Parce que tu m’acceptes tel que je suis",
    /* 106 */ "Pour ton énergie qui me booste",
    /* 107 */ "Parce que tu es mon endroit préféré",
    /* 108 */ "Pour la chaleur de ton regard",
    /* 109 */ "Parce que tu me fais sentir aimé chaque jour",
    /* 110 */ "Pour ta spontanéité qui rend tout plus vivant",
    /* 111 */ "Parce que tu es mon évidence",
    /* 112 */ "Pour la manière dont tu me fais sourire sans effort",
    /* 113 */ "Parce que tu rends l’avenir excitant",
    /* 114 */ "Pour ton honnêteté qui me rassure",
    /* 115 */ "Parce que tu es ma plus grande fierté",
    /* 116 */ "Pour ta façon de me taquiner",
    /* 117 */ "Parce que tu es mon plus beau chapitre",
    /* 118 */ "Pour tes petites manies que j’adore secrètement",
    /* 119 */ "Parce que tu fais battre mon cœur plus vite 💗💗",
    /* 120 */ "Pour la sécurité que je ressens avec toi",
    /* 121 */ "Parce que chaque matin commence mieux avec toi",
    /* 122 */ "Pour nos regards complices 🤩",
    /* 123 */ "Parce que tu rends chaque promenade spéciale",
    /* 124 */ "Pour nos discussions tard dans la nuit 😴",
    /* 125 */ "Parce que tu me donnes confiance en nous",
    /* 126 */ "Pour les photos qu’on prend sans raison 📸",
    /* 127 */ "Parce que tu rends les silences confortables",
    /* 128 */ "Pour ton rire incontrôlable",
    /* 129 */ "Parce que tu es ma plus belle habitude",
    /* 130 */ "Pour la paix que je ressens à tes côtés",
    /* 131 */ "Parce que tu me fais sentir unique",
    /* 132 */ "Pour ton regard quand tu es fière de nous",
    /* 133 */ "Parce que tu transformes tout en aventure",
    /* 134 */ "Pour nos inside jokes incompréhensibles pour les autres",
    /* 135 */ "Parce que tu rends le quotidien extraordinaire",
    /* 136 */ "Pour la tendresse dans tes messages",
    /* 137 */ "Parce que tu m’encourages toujours",
    /* 138 */ "Pour nos projets imaginés à deux",
    /* 139 */ "Parce que tu es mon meilleur choix 😘",
    /* 140 */ "Pour les souvenirs qu’on garde juste pour nous",
    /* 141 */ "Parce que tu sais quand j’ai besoin d’un câlin",
    /* 142 */ "Pour ton sourire fatigué mais heureux",
    /* 143 */ "Parce que tu crois en notre histoire",
    /* 144 */ "Pour ton regard quand tu es concentrée",
    /* 145 */ "Parce que tu es ma plus belle surprise",
    /* 146 */ "Pour ton soutien silencieux",
    /* 147 */ "Parce que tu m’aimes même les jours difficiles",
    /* 148 */ "Pour ta façon de me rendre plus calme",
    /* 149 */ "Parce que tu es mon plus beau voyage",
    /* 150 */ "Pour ton énergie douce",
    /* 151 */ "Parce que tu es mon refuge",
    /* 152 */ "Pour la force de ton amour",
    /* 153 */ "Parce que tu rends mon cœur léger",
    /* 154 */ "Pour la profondeur de nos conversations",
    /* 155 */ "Parce que tu es ma plus belle promesse",
    /* 156 */ "Pour ton regard rempli d’amour",
    /* 157 */ "Parce que tu es mon évidence chaque jour",
    /* 158 */ "Pour la façon dont tu me regardes quand tu es heureuse",
    /* 159 */ "Parce que tu es mon futur préféré",
    /* 160 */ "Pour ta manière de me rassurer sans mots",
    /* 161 */ "Parce que tu sais être forte et douce à la fois",
    /* 162 */ "Pour les petites victoires que tu célèbres avec moi",
    /* 163 */ "Parce que tu me fais sentir capable",
    /* 164 */ "Pour ton humour au moment où je m’y attends le moins",
    /* 165 */ "Parce que tu sais me ramener à l’essentiel",
    /* 166 */ "Pour la façon dont tu prends soin de toi et de nous",
    /* 167 */ "Parce que tu es mon calme au milieu du bruit",
    /* 168 */ "Pour ton regard qui dit « on est ensemble »",
    /* 169 */ "Parce que tu m’apprends à aimer mieux",
    /* 170 */ "Pour les petits rituels qu’on a créés",
    /* 171 */ "Parce que tu me donnes envie de faire des efforts",
    /* 172 */ "Pour ta façon de dire « ça va aller »",
    /* 173 */ "Parce que tu rends mes peurs moins grandes",
    /* 174 */ "Pour ton sens du détail qui me touche",
    /* 175 */ "Parce que tu sais quand j’ai besoin d’espace et quand j’ai besoin de toi",
    /* 176 */ "Pour la manière dont tu transformes une maison en foyer",
    /* 177 */ "Parce que tu es ma chance 🍀",
    /* 178 */ "Pour la douceur de ta présence, même à distance",
    /* 179 */ "Parce que tu me fais aimer le temps qui passe",
    /* 180 */ "Pour nos plans spontanés qui finissent en souvenirs",
    /* 181 */ "Parce que tu es ma petite déesse 🧚",
    /* 182 */ "Pour la façon dont tu m’encourages à croire en moi",
    /* 183 */ "Parce que tu vois le meilleur en moi",
    /* 184 */ "Pour ton sourire quand tu es fière de toi",
    /* 185 */ "Parce que tu es ma plus belle motivation",
    /* 186 */ "Pour ta façon de t’émerveiller pour des petites choses",
    /* 187 */ "Parce que tu rends les attentes plus courtes",
    /* 188 */ "Pour ton regard quand tu découvres quelque chose de nouveau",
    /* 189 */ "Parce que tu as un cœur immense ❤️ <3",
    /* 190 */ "Pour la façon dont tu prends ma défense sans hésiter",
    /* 191 */ "Parce que tu me fais me sentir choisi",
    /* 192 */ "Pour ta tendresse quand tu penses que je dors",
    /* 193 */ "Parce que tu es ma meilleure nouvelle",
    /* 194 */ "Pour ton rire qui me guérit un peu",
    /* 195 */ "Parce que tu rends les « lundi » plus doux",
    /* 196 */ "Pour les moments où tu me regardes et tu souris sans raison",
    /* 197 */ "Parce que tu es mon « oui » préféré",
    /* 198 */ "Pour ta façon de dire les choses avec gentillesse",
    /* 199 */ "Parce que tu es une personne rare",
    /* 200 */ "Pour la confiance que je ressens quand je suis avec toi",
    /* 201 */ "Parce que tu m’inspires à être plus patient",
    /* 202 */ "Pour la manière dont tu prends le temps",
    /* 203 */ "Parce que tu sais rendre les choses simples",
    /* 204 */ "Pour tes petites danses de joie",
    /* 205 */ "Parce que tu rends mes réussites plus belles",
    /* 206 */ "Pour ta façon d’apaiser les tensions",
    /* 207 */ "Parce que tu sais dire pardon avec le cœur 💞",
    /* 208 */ "Pour ton respect, même quand on n’est pas d’accord",
    /* 209 */ "Parce que tu me fais sentir compris",
    /* 210 */ "Pour les aventures qu’on a déjà vécues",
    /* 211 */ "Parce que tu me donnes envie de construire 🏡",
    /* 212 */ "Pour ton sourire sur les photos volées",
    /* 213 */ "Parce que tu me fais t'aimer encore et encore plus 🥰",
    /* 214 */ "Pour la façon dont tu tiens mon bras en marchant",
    /* 215 */ "Parce que tu as une beauté infini 😍",
    /* 216 */ "Pour ta gentillesse avec ceux que tu aimes",
    /* 217 */ "Parce que tu me fais sentir à ma place",
    /* 218 */ "Pour ta capacité à pardonner",
    /* 219 */ "Parce que tu sais reconnaître mes efforts",
    /* 220 */ "Pour ta façon de rendre la vie plus douce",
    /* 221 */ "Parce que tu as toujours une attention qui change tout",
    /* 222 */ "Pour la façon dont tu te réjouis de mes joies",
    /* 223 */ "Parce que tu es mon meilleur coup de chance",
    /* 224 */ "Pour les moments où tu me serres fort sans prévenir",
    /* 225 */ "Parce que tu me fais me sentir vivant",
    /* 226 */ "Pour tes « tu me manques » qui me retournent le cœur",
    /* 227 */ "Parce que tu sais être sérieuse et légère au bon moment",
    /* 228 */ "Pour ta façon d’aimer sans compter",
    /* 229 */ "Parce que tu es la personne avec qui je veux tout partager",
    /* 230 */ "Pour le bruit de ton rire dans la pièce d’à côté",
    /* 231 */ "Parce que tu rends les petits cadeaux immenses",
    /* 232 */ "Pour ta manière de dire « je t'aime mon doudou ❤️❤️ »",
    /* 233 */ "Parce que tu me fais croire aux belles choses",
    /* 234 */ "Pour ton regard quand tu es émue",
    /* 235 */ "Parce que tu es mon réconfort préféré",
    /* 236 */ "Pour la façon dont tu changes l’atmosphère en arrivant",
    /* 237 */ "Parce que tu me fais oublier mon téléphone",
    /* 238 */ "Pour les moments où tu me regardes comme si j’étais tout",
    /* 239 */ "Parce que tu es mon plus beau « aujourd’hui »",
    /* 240 */ "Pour ta façon de rendre nos souvenirs précieux",

    /* 241 */ "Parce que tu sais être présente, vraiment",
    /* 242 */ "Pour tes petites grimaces quand tu n’es pas convaincue 🤪🤪",
    /* 243 */ "Parce que tu as cette étincelle qui rend tout possible ✨",
    /* 244 */ "Pour ta façon de me redonner de l’énergie",
    /* 245 */ "Parce que tu me rends fier d’aimer",
    /* 246 */ "Pour la façon dont tu parles de ce que tu aimes",
    /* 247 */ "Parce que tu as une douceur qui me désarme",
    /* 248 */ "Pour tes messages vocaux qui me font sourire",
    /* 249 */ "Parce que tu sais rendre un simple dîner magique",
    /* 250 */ "Pour la manière dont tu prends le temps de comprendre",
    /* 251 */ "Parce que tu as une présence qui rassure",
    /* 252 */ "Pour tes sourires timides",
    /* 253 */ "Parce que tu es ma meilleure idée",
    /* 254 */ "Pour la façon dont tu m’aides à grandir, et à ne plus faire le bébé 😂🫣",
    /* 255 */ "Parce que tu me fais aimer mes propres défauts",
    /* 256 */ "Pour ton rire quand je fais n’importe quoi",
    /* 257 */ "Parce que tu es la personne que je choisis, tous les jours",
    /* 258 */ "Pour ta façon de rendre les excuses faciles",
    /* 259 */ "Parce que tu sais dire la vérité avec douceur",
    /* 260 */ "Pour la paix que tu poses sur ma vie",
    /* 261 */ "Parce que tu m’offres des souvenirs qui dureront toute une vie",
    /* 262 */ "Pour ta façon de me regarder quand je parle de mes passions",
    /* 263 */ "Parce que tu sais me recentrer quand je pars dans tous les sens",
    /* 264 */ "Pour ta main qui cherche la mienne",
    /* 265 */ "Parce que tu rends les jours fériés encore plus beaux",
    /* 266 */ "Pour les moments où tu chantes sans t’en rendre compte",
    /* 267 */ "Parce que tu es ma personne, simplement",
    /* 268 */ "Pour tes encouragements quand je doute",
    /* 269 */ "Parce que tu sais me faire rire en une phrase",
    /* 270 */ "Pour la façon dont tu m’accueilles",
    /* 271 */ "Parce que tu me donnes envie d’être tendre",
    /* 272 */ "Pour tes idées qui rendent nos journées différentes",
    /* 273 */ "Parce que tu as un cœur qui comprend",
    /* 274 */ "Pour la façon dont tu me fais sentir en sécurité",
    /* 275 */ "Parce que tu sais rendre les efforts légers",
    /* 276 */ "Pour ta délicatesse quand tu parles de nous",
    /* 277 */ "Parce que tu es la plus belle partie de mes journées 🌞",
    /* 278 */ "Pour ta façon de dire « Bobby 😏 »",
    /* 279 */ "Parce que tu me fais croire en demain",
    /* 280 */ "Pour la douceur de nos habitudes",
    /* 281 */ "Parce que tu as cette force de continuer même quand c’est dur",
    /* 282 */ "Pour la façon dont tu t’émerveilles devant un coucher de soleil",
    /* 283 */ "Parce que tu me donnes envie d’être meilleur, sans pression",
    /* 284 */ "Pour tes petits soupirs de contentement",
    /* 285 */ "Parce que tu sais rendre une mauvaise journée supportable",
    /* 286 */ "Pour tes yeux qui disent tout",
    /* 287 */ "Parce que tu es mon plus bel engagement",
    /* 288 */ "Pour ton respect de mes limites",
    /* 289 */ "Parce que tu me fais sentir important, même dans les détails",
    /* 290 */ "Pour ta façon de te réjouir des choses simples",
    /* 291 */ "Parce que tu sais être douce quand je suis dur avec moi-même",
    /* 292 */ "Pour ton courage d’être toi",
    /* 293 */ "Pour l'amour inconditionnel que tu me donnes chaque jour ❤️‍🔥",
    /* 294 */ "Pour ta façon de rire avec tout ton cœur",
    /* 295 */ "Parce que tu me fais aimer la vie un peu plus",
    /* 296 */ "Pour ta capacité à transformer un problème en solution",
    /* 297 */ "Parce que tu sais me calmer avec un seul mot",
    /* 298 */ "Pour les moments où tu me regardes comme si tu savais",
    /* 299 */ "Parce que tu es ma douceur préférée",
    /* 300 */ "Pour la façon dont tu me choisis, toi aussi",
    /* 301 */ "Parce qu’avec toi je me sens à la maison",
    /* 302 */ "Pour les jours où tu me manques et où je le sens partout",
    /* 303 */ "Parce que tu es mon plus beau « pour toujours »",
    /* 304 */ "Pour ta façon de m’aimer même quand je suis fatigué",
    /* 305 */ "Parce que tu sais être mon calme et mon feu",
    /* 306 */ "Pour la manière dont tu m’aides à croire en l’amour",
    /* 307 */ "Parce que tu es mon futur en mieux",
    /* 308 */ "Pour ta tendresse quand tu fais semblant d’être sérieuse",
    /* 309 */ "Parce que tu me donnes envie de prendre soin de nous",
    /* 310 */ "Pour ta façon de me regarder comme si j’étais unique",
    /* 311 */ "Parce que tu sais trouver la lumière même dans le doute",
    /* 312 */ "Pour tes « ça ira » qui me soulagent",
    /* 313 */ "Parce que tu es ma plus belle aventure à long terme",
    /* 314 */ "Pour les moments où tu me serres la main un peu plus fort. Bon révéillon mon doudou !",
    /* 315 */ "Parce que tu es le plus beau cadeau qu'on m'ait offert. Joyeux Noêl ! 🎄🎁",
    /* 316 */ "Pour ta manière de rendre les souvenirs vivants",
    /* 317 */ "Parce que tu es la personne que je veux retrouver chaque soir",
    /* 318 */ "Pour la douceur de ton prénom dans ma bouche",
    /* 319 */ "Parce que tu m’aides à devenir moi, en mieux",
    /* 320 */ "Pour ton amour qui me rend plus fort",
    /* 321 */ "Parce que tu es mon plus beau choix de vie",
    /* 322 */ "Pour la façon dont tu respectes mes rêves. Bon année et bonne santé à la femme de ma vie ! ❤️🍾",
    /* 323 */ "Parce que tu as un rire qui me fait oublier le reste",
    /* 324 */ "Pour tes petites attentions que tu crois invisibles",
    /* 325 */ "Parce que tu me donnes envie de créer des traditions",
    /* 326 */ "Pour ton sourire quand tu goûtes quelque chose de bon",
    /* 327 */ "Parce que tu sais me dire la vérité avec amour",
    /* 328 */ "Pour la patience que tu mets dans notre histoire",
    /* 329 */ "Parce que tu es à moi et à personne d'autre 🥰 »",
    /* 330 */ "Pour la façon dont tu rends tout plus beau",
    /* 331 */ "Parce que tu me fais sentir aimé même sans mots",
    /* 332 */ "Pour tes yeux qui rient avant ta bouche",
    /* 333 */ "Parce que tu es mon bonheur au quotidien",
    /* 334 */ "Pour la façon dont tu prends soin de notre lien",
    /* 335 */ "Parce que tu me fais aimer les petits matins",
    /* 336 */ "Parce qu'après 24 ans d'existance, tu es la personne la plus formidable ⭐",
    /* 337 */ "Parce que tu es mon meilleur souvenir en construction",
    /* 338 */ "Pour ta façon de me rappeler ce qui compte",
    /* 339 */ "Parce que tu es ma personne préférée, encore",
    /* 340 */ "Pour l’avenir que je vois quand je te regarde",
    /* 341 */ "Parce que tu es le plus beau « oui » de ma vie",
    /* 342 */ "Pour la façon dont tu rends l’amour simple",
    /* 343 */ "Parce que tu es la paix que je cherchais sans le savoir",
    /* 344 */ "Pour ta manière de me faire sentir entier",
    /* 345 */ "Parce que tu es mon coup de cœur permanent 😍",
    /* 346 */ "Pour tous les jours où tu m’as rendu heureux sans t’en rendre compte",
    /* 347 */ "Parce que tu es mon meilleur endroit dans le monde",
    /* 348 */ "Pour la façon dont tu me fais croire en nous",
    /* 349 */ "Parce que tu es ma plus belle évidence",
    /* 350 */ "Pour ton amour qui ne fait pas de bruit, mais fait tout",
    /* 351 */ "Parce que tu es mon bonheur le plus sûr",
    /* 352 */ "Pour ta main qui trouve la mienne même dans la foule",
    /* 353 */ "Parce que tu as rendu ma vie plus lumineuse ✨✨",
    /* 354 */ "Pour la façon dont tu me fais sourire même de loin",
    /* 355 */ "Parce que je t’aime de la tête au pied 🙃😘",
    /* 356 */ "Pour ton regard qui me donne envie de rester",
    /* 357 */ "Parce que tu es ma plus belle mélodie, à travers le battement de mon coeur 🪉❤️",
    /* 358 */ "Pour tout ce que tu es, quand personne ne regarde",
    /* 359 */ "Parce que tu es ma meilleure habitude et mon plus beau vertige",
    /* 360 */ "Pour la façon dont tu fais battre mon cœur, encore aujourd’hui ❤️‍🔥❤️‍🔥",
    /* 361 */ "Parce que chaque jour avec toi est une chance 🫶",
    /* 362 */ "Pour tout ce que tu as déjà apporté à ma vie 🙏",
    /* 363 */ "Parce que je te choisirais encore, dans n’importe quelle version du monde 🗺️",
    /* 364 */ "Parce que je t’aime, simplement — aujourd’hui, demain, et pour longtemps ♾️",
    /* 365 */ "Parce que 365 raisons ne suffisent pas pour dire à quel point je t'aime ❤️",
];
